name: brews
description: PLaying around Cubit.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

  bloc: ^6.0.1
  dio: ^3.0.10
  flutter_bloc: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  lint: ^1.2.0

flutter:
  uses-material-design: true